export { ReactComponent as cloche } from './Cloche.svg';
export { ReactComponent as food } from './Food.svg';
export { ReactComponent as chevron_left } from './Chevron-left.svg';
export { ReactComponent as chevron_right } from './Chevron-right.svg';
export { ReactComponent as plus } from './Plus.svg';
export { ReactComponent as help } from './Help.svg';
export { ReactComponent as person } from './Person.svg';
export { ReactComponent as menu } from './Menu.svg';
export { ReactComponent as home } from './Home.svg';
export { ReactComponent as home_on } from './Home-on.svg';
export { ReactComponent as ticket } from './Ticket.svg';
export { ReactComponent as ticket_on } from './Ticket-on.svg';
export { ReactComponent as mypage } from './Mypage.svg';
export { ReactComponent as mypage_on } from './Mypage-on.svg';
export { ReactComponent as email } from './Email.svg';
export { ReactComponent as search } from './Search.svg';
export { ReactComponent as kakao } from './Kakao.svg';
export { ReactComponent as like } from './Like.svg';
export { ReactComponent as comment } from './Comment.svg';
export { ReactComponent as back } from './Back.svg';
export { ReactComponent as delete } from './Delete.svg';
export { ReactComponent as history } from './History.svg';
export { ReactComponent as chart } from './Chart.svg';
export { ReactComponent as send } from './Send.svg';
export { ReactComponent as announcement } from './Announcement.svg';
export { ReactComponent as id } from './Id.svg';
export { ReactComponent as password } from './Password.svg';
export { ReactComponent as login } from './Login.svg';
export { ReactComponent as next } from './Next.svg';
export { ReactComponent as write } from './Write.svg';
export { ReactComponent as info } from './Info.svg';
export { ReactComponent as calendar } from './Calendar.svg';
export { ReactComponent as location } from './Location.svg';
export { ReactComponent as cba_logo } from './CbaLogo.svg';
// export { ReactComponent as cba_logo } from './BlueCBALogo.svg';
export { ReactComponent as document } from './Document.svg';
export { ReactComponent as graph } from './Graph.svg';
export { ReactComponent as meal } from './Meal.svg';
export { ReactComponent as youtube } from './Youtube.svg';
export { ReactComponent as logout } from './Logout.svg';
export { ReactComponent as cake } from './Cake.svg';
export { ReactComponent as user } from './User.svg';
export { ReactComponent as gender } from './Gender.svg';
export { ReactComponent as check } from './Check.svg';
export { ReactComponent as users } from './Users.svg';
export { ReactComponent as chevron_up } from './Chevron-up.svg';
export { ReactComponent as chevron_down } from './Chevron-down.svg';
export { ReactComponent as clock } from './Clock.svg';
export { ReactComponent as bill } from './Bill.svg';
export { ReactComponent as spinner } from './Spinner.svg';
export { ReactComponent as message } from './Message.svg';
export { ReactComponent as trash } from './Trash.svg';
export { ReactComponent as holydaypassTicket } from './holydaypass.svg';
// export { ReactComponent as home_guide } from './HomeGuide.svg';
export { ReactComponent as home_guide } from './Home_RetreatGuideBook.svg';
export { ReactComponent as home_holyday } from './HomeHolyday.svg';
export { ReactComponent as home_pass } from './HomePassv2.svg';
// export { ReactComponent as home_live } from './HomeLive.svg';
export { ReactComponent as home_live } from './Home_RetreatOnAir.svg';
// export { ReactComponent as home_payment } from './HomePayment.svg';
export { ReactComponent as home_payment } from './Home_CheckPayment.svg';
// export { ReactComponent as home_prayer } from './HomePrayer.svg';
// export { ReactComponent as home_prayer } from './Home_PrayMotion.svg';
export { ReactComponent as home_carpool } from './CarPool.svg';
export { ReactComponent as notice } from './notice.svg';
export { ReactComponent as check_lined } from './Check-lined.svg';
export { ReactComponent as application_check } from './ApplicationCheck.svg';
